web/fNordLager/config/routes.rb
FNordLager::Application.routes.draw do
  get "loading_ramp/ramp"

  post "loading_ramp/good_in"

  post "loading_ramp/good_out"

  resources :things

  root :to => 'things#index'

end

web/fNordLager/app/models/thing.rb
class Thing < ActiveRecord::Base
end

web/fNordLager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web/fNordLager/app/controllers/loading_ramp_controller.rb
class LoadingRampController < ApplicationController
  def ramp
    @last_things = Thing.order("updated_at DESC")
  end

  def good_in
    qty = params[:thing_in][:quantity].present? ?
            BigDecimal.new(params[:thing_in][:quantity]) : 1
    @thing = good_quantity(params[:thing_in][:barcode], qty)

    respond_to do |format|
      format.html { redirect_to loading_ramp_ramp_path }
      format.json { render json: @thing }
    end
  end

  def good_out
    qty = params[:thing_out][:quantity].present? ?
            -BigDecimal.new(params[:thing_out][:quantity]) : -1
    @thing = good_quantity(params[:thing_out][:barcode], qty)

    respond_to do |format|
      format.html { redirect_to loading_ramp_ramp_path }
      format.json { render json: @thing }
    end
  end


  private

  def good_quantity(bc, qty)
    @thing = Thing.find_by_barcode(bc)
    @thing.quantity += qty
    @thing.save
    @thing
  end
end

web/fNordLager/app/controllers/things_controller.rb
class ThingsController < ApplicationController
  # GET /things
  # GET /things.json
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @things }
    end
  end

  # GET /things/1
  # GET /things/1.json
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/new
  # GET /things/new.json
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render json: @thing, status: :created, location: @thing }
      else
        format.html { render action: "new" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.json
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to things_url }
      format.json { head :no_content }
    end
  end
end

web/fNordLager/app/helpers/application_helper.rb
module ApplicationHelper
end

web/fNordLager/app/helpers/loading_ramp_helper.rb
module LoadingRampHelper
end

web/fNordLager/app/helpers/things_helper.rb
module ThingsHelper
end

web/fNordLager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FNordLager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

web/fNordLager/app/views/loading_ramp/good_in.html.erb
<h1>LoadingRamp#good_in</h1>
<p>Find me in app/views/loading_ramp/good_in.html.erb</p>

web/fNordLager/app/views/loading_ramp/good_out.html.erb
<h1>LoadingRamp#good_out</h1>
<p>Find me in app/views/loading_ramp/good_out.html.erb</p>

web/fNordLager/app/views/loading_ramp/ramp.html.erb
<h1>LoadingRamp#ramp</h1>

<%= form_for "thing_in", :url => loading_ramp_good_in_path do |f| %>
  <%= f.label :barcode %>
  <%= f.text_field :barcode %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity, :size => 3 %>
  <%= f.submit 'Thing in' %>
<%- end %>

<%= form_for "thing_out", :url => loading_ramp_good_out_path do |f| %>
  <%= f.label :barcode %>
  <%= f.text_field :barcode %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity, :size => 3 %>
  <%= f.submit 'Thing out' %>
<%- end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Barcode</th>
      <th>Quantity</th>
    </tr>
  </thead>
  <tbody>
    <%- @last_things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= thing.description %></td>
        <td><%= thing.barcode %></td>
        <td><%= thing.quantity %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

<script type="text/javascript">
  $(function () {
    $("#thing_in_barcode").focus();
  });
</script>

web/fNordLager/app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :barcode %><br />
    <%= f.text_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/fNordLager/app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

web/fNordLager/app/views/things/index.html.erb
<h1>Listing things</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Barcode</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @things.each do |thing| %>
  <tr>
    <td><%= thing.name %></td>
    <td><%= thing.description %></td>
    <td><%= thing.barcode %></td>
    <td><%= thing.quantity %></td>
    <td><%= link_to 'Show', thing %></td>
    <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
    <td><%= link_to 'Destroy', thing, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thing', new_thing_path %>

web/fNordLager/app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

web/fNordLager/app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @thing.name %>
</p>

<p>
  <b>Description:</b>
  <%= @thing.description %>
</p>

<p>
  <b>Barcode:</b>
  <%= @thing.barcode %>
</p>

<p>
  <b>Quantity:</b>
  <%= @thing.quantity %>
</p>


<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>